### ISSUE TITLE
question Not a issue 

### ISSUE THREAD

**Issue by EWANZO101** [therootcompany/proxmox-sh#30]
Hello, I came across this on YouTube. I would really love to use this script for VMs. Is this possible? Additionally, where would I install this if I wanted to make it into a website and create a user portal, etc.? Do you have any other OPS projects that I could use to achieve this, as I am not the most experienced when it comes to automation and website backends?

I have already tried out most of the billing panels that have this feature, but most are too expensive or too buggy.

**Comment by coolaj86** [comment]
This isn't really in a state where someone else could install and use it outside of our group.

If you already have a Proxmox cluster set up, I'd be willing to help you through some of the OPNSense and Caddy setup to get this to work for you (or disable those parts so that you can have it work the way you want). However, if you're not familiar with Proxmox in general, it probably won't be of much use to you.
